services:
  certificado:
    build:
      context: .
      dockerfile: Dockerfile
    image: certificado-nginx
    container_name: certificado
    restart: unless-stopped
    ports:
      - "17854:80"
